<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dev.gscordeiro</groupId>
    <artifactId>faces-motors</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <packaging>war</packaging>
    <name>Faces Motors</name>
    <description>Código fonte do livro Aplicações Java para a web com JSF e JPA - 2ª Edição</description>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <jakartaee-api.version>11.0.0</jakartaee-api.version>
        <primefaces.version>15.0.14</primefaces.version>

        <wildfly.version>36.0.1.Final</wildfly.version>
        <hibernate.version>6.6.7.Final</hibernate.version>

        <galleon-datasources.version>10.0.0.Final</galleon-datasources.version>
        <wildfly-jar-plugin.version>12.0.0.Final</wildfly-jar-plugin.version>

        <version.junit>5.10.1</version.junit>
    </properties>

    <dependencies>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-web-api</artifactId>
            <version>${jakartaee-api.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>${hibernate.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces</artifactId>
            <version>${primefaces.version}</version>
            <classifier>jakarta</classifier>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.16</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
            <version>2.0.16</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${version.junit}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <release>${java.version}</release>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <parameters>true</parameters>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.hibernate.orm</groupId>
                            <artifactId>hibernate-jpamodelgen</artifactId>
                            <version>6.6.14.Final</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.4.0</version>
            </plugin>

            <plugin>
                <groupId>org.wildfly.plugins</groupId>
                <artifactId>wildfly-jar-maven-plugin</artifactId>
                <version>${wildfly-jar-plugin.version}</version>
                <configuration>
                    <hollow-jar>${wildfly.bootable.hollow}</hollow-jar>
                    <skip>${wildfly.bootable.package.skip}</skip>
                    <cli-sessions>
                    </cli-sessions>
                    <jvmArguments>
                        <arg>-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n</arg>
                    </jvmArguments>
                    <feature-packs>
                        <feature-pack>
                            <location>wildfly-preview@maven(org.jboss.universe:community-universe)#${wildfly.version}</location>
                        </feature-pack>
                        <feature-pack>
                            <location>org.wildfly:wildfly-datasources-preview-galleon-pack:${galleon-datasources.version}</location>
                        </feature-pack>
                    </feature-packs>
                    <layers>
                        <layer>jakarta-data</layer>
                        <layer>jpa</layer>
                        <layer>jsf</layer>
                        <layer>h2-driver</layer>
                    </layers>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
