# Datasource H2 (banco em memória, criado automaticamente na inicialização)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:~/temp/facesmotors_db;AUTO_SERVER=TRUE
quarkus.datasource.username=sa
quarkus.datasource.password=

# Hibernate ORM
#quarkus.hibernate-orm.database.generation=drop-and-create
#quarkus.hibernate-orm.second-level-caching-enabled=true

# H2 Console - disponível em http://localhost:8080/q/dev-ui/quarkus-agroal/database-view
