# Datasource MySQL
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost/facesmotors?createDatabaseIfNotExist=true
quarkus.datasource.username=root
quarkus.datasource.password=root

# Hibernate ORM - cache de segundo nível
quarkus.hibernate-orm.second-level-caching-enabled=true
